config/routes.rb
Rails.application.routes.draw do

  root 'pages#homepage'

  get '/homepage', to: 'pages#homepage'

  get '/about', to: 'pages#about'

  get '/done', to: 'pages#done'

  get '/like', to: 'pages#like'

  get '/contact', to: 'pages#contact'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def homepage
  end

  def about
  end

  def done
  end

  def like
  end

  def contact
  @email = "l.a.walpole@googlemail.com"

  end



end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LauraApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
</head>
<body>
<nav class="<%= params[:action]%>">
  <ul>
    <li><%= link_to("THE STORY SO FAR", about_path)%></li><li><%= link_to("THE STUFF IVE DONE", done_path)%></li><li><%= link_to("THINGS I LIKE", like_path)%></li><li><%= link_to("REACH OUT", contact_path)%></li>
  </ul>
</nav>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

app/views/pages/contact.html.erb
<div class="contact">
  <h2>Reach Out</h2>

  <div class="email">
    <h3>Get intouch @ <%= @email %></h3>
    <h3>Or drop me a line on 07733327682</h3>
  </div>
</div>

app/views/pages/done.html.erb
<h2>So this is what i've done...</h2>

app/views/pages/homepage.html.erb
<div class="bigtext">
  <h1><a href="/about">| THE STORY SO FAR</a></h1><h1><a href="/done">| THE STUFF IVE DONE</a></h1><h1><a href="/like">| THINGS I LIKE</a></h1><h1><a href="/contact">| REACH OUT</a></h1>
</div>  

app/views/pages/like.html.erb
<h2>Things I like...</h2>